### ISSUE TITLE
Capitale instead of capital 

### ISSUE THREAD

**Issue by iamlamino** [daoodaba975/galsenify#20]
In the différents objects where you might wanna display the capital city, you named the capital capital instead of capitale. I assume different naming are in french so  i guess yo should dchange it to capitale with an e at the end. 

Great project, keep going you are inspirational !

**Comment by daoodaba975** [comment]
Hi @iamlamino 
Thank you for pointing this out and for your kind words about the project!

You’re absolutely right; consistency in naming is crucial, and the correction from capital to capitale makes sense given the context. I'll ensure this change is implemented in the next version.
