### ISSUE TITLE
Chore() - Update package structure

### ISSUE THREAD

**Issue by papac** [daoodaba975/galsenify#5]
The  `src` should be `dataset`, `src` let know your code location. 

But in this own case, there is no js or lib located in `src` that can create confusion.

My proposed structure:

```
- lib
- dataset/regions.json
- dataset/senegal.json
```

Update the `index.js`

```
const sn = require("./dataset/senegal.json");
const rg = require("./dataset/regions.json");
```

**Comment by daoodaba975** [comment]
> The `src` should be `dataset`, `src` let know your code location.
> 
> But in this own case, there is no js or lib located in `src` that can create confusion.
> 
> My proposed structure:
> 
> ```
> - lib
> - dataset/regions.json
> - dataset/senegal.json
> ```
> 
> Update the `index.js`
> 
> ```
> const sn = require("./dataset/senegal.json");
> const rg = require("./dataset/regions.json");
> ```

Very well explained @papac  indeed it can lead to confusion 👍
Thanks!
